"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
from pathlib import Path
import os
import sys

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-nq-b@rbpm+4xiday4pxzooolcr%sw)+qo1a$^hi0m5_(zg+kdw',
)

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development').lower()
DEBUG = os.environ.get('DJANGO_DEBUG', 'true' if DJANGO_ENV != 'production' else 'false').lower() == 'true'

# Pending payments are no longer usable after this interval.
PAYMENT_EXPIRY_MINUTES = int(os.environ.get('PAYMENT_EXPIRY_MINUTES', '6'))

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        '10.119.105.158,localhost,127.0.0.1,dn.cs.ui.ac.id,leopard40.cs.ui.ac.id',
    ).split(',')
    if host.strip()
]
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'https://dn.cs.ui.ac.id,https://leopard40.cs.ui.ac.id',
    ).split(',')
    if origin.strip()
]

if DJANGO_ENV == 'production':
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
    'django_extensions',
]

SSO_PROVIDER = os.environ.get('SSO_PROVIDER', 'cas').lower()
if SSO_PROVIDER not in {'cas', 'keycloak'}:
    raise ValueError('SSO_PROVIDER harus bernilai cas atau keycloak.')

if SSO_PROVIDER == 'keycloak':
    INSTALLED_APPS.append('mozilla_django_oidc')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if 'test' in sys.argv and os.environ.get('DJANGO_TEST_USE_POSTGRES', '').lower() != 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
elif os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL = 'registration.CustomUser'

LOGIN_URL = 'login'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# Development continues using the current CAS2 SSO UI endpoint.
SSO_UI_URL = 'https://sso.ui.ac.id/cas2/'
SSO_UI_FORCE_SERVICE_HTTPS = os.environ.get('SSO_UI_FORCE_SERVICE_HTTPS', 'false').lower() == 'true'

# Production uses Keycloak OIDC Authorization Code with PKCE. Keycloak values must
# be supplied through .env.prod and are intentionally not committed to this repository.
if SSO_PROVIDER == 'keycloak':
    KEYCLOAK_URL = os.environ.get('KEYCLOAK_URL', '').rstrip('/')
    KEYCLOAK_REALM = os.environ.get('KEYCLOAK_REALM', '')
    KEYCLOAK_CLIENT_ID = os.environ.get('KEYCLOAK_CLIENT_ID', '')
    if not all((KEYCLOAK_URL, KEYCLOAK_REALM, KEYCLOAK_CLIENT_ID)):
        raise ValueError('KEYCLOAK_URL, KEYCLOAK_REALM, dan KEYCLOAK_CLIENT_ID wajib diisi.')

    KEYCLOAK_USERNAME_CLAIM = os.environ.get('KEYCLOAK_USERNAME_CLAIM', 'preferred_username')
    KEYCLOAK_NPM_CLAIM = os.environ.get('KEYCLOAK_NPM_CLAIM', 'npm')
    KEYCLOAK_ROLE_CLAIM = os.environ.get('KEYCLOAK_ROLE_CLAIM', 'roles')
    KEYCLOAK_STUDENT_ROLES = os.environ.get('KEYCLOAK_STUDENT_ROLES', 'mahasiswa,student')
    KEYCLOAK_LECTURER_ROLES = os.environ.get('KEYCLOAK_LECTURER_ROLES', 'dosen,lecturer')
    KEYCLOAK_ALUMNI_ROLES = os.environ.get('KEYCLOAK_ALUMNI_ROLES', 'alumni')
    _KEYCLOAK_OIDC_BASE = f'{KEYCLOAK_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect'

    OIDC_RP_CLIENT_ID = KEYCLOAK_CLIENT_ID
    OIDC_RP_CLIENT_SECRET = os.environ.get('KEYCLOAK_CLIENT_SECRET', '')
    OIDC_RP_SCOPES = 'openid profile email'
    OIDC_RP_SIGN_ALGO = 'RS256'
    OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KEYCLOAK_OIDC_BASE}/auth'
    OIDC_OP_TOKEN_ENDPOINT = f'{_KEYCLOAK_OIDC_BASE}/token'
    OIDC_OP_USER_ENDPOINT = f'{_KEYCLOAK_OIDC_BASE}/userinfo'
    OIDC_OP_JWKS_ENDPOINT = f'{_KEYCLOAK_OIDC_BASE}/certs'
    OIDC_USE_PKCE = True
    OIDC_STORE_ACCESS_TOKEN = False
    OIDC_STORE_ID_TOKEN = False
    OIDC_REDIRECT_REQUIRE_HTTPS = DJANGO_ENV == 'production'
    OIDC_REDIRECT_ALLOWED_HOSTS = ALLOWED_HOSTS
    AUTHENTICATION_BACKENDS = (
        'registration.oidc.FasilkomOIDCAuthenticationBackend',
        'django.contrib.auth.backends.ModelBackend',
    )
