# Generated by Django 6.1 on 2026-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tshirt_size',
            field=models.CharField(choices=[('NONE', 'Tidak Ada Kaos'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL+', 'XXL+')], default='NONE', max_length=10),
        ),
    ]
