# Generated by Django 6.1 on 2026-08-18 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_ticket_tshirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSpreadsheetBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nama Backup')),
                ('file', models.FileField(upload_to='admin_exports/', verbose_name='File Spreadsheet')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Transaksi')),
                ('response_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Baris Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transaction_backups', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Backup Spreadsheet Response',
                'verbose_name_plural': 'Backup Spreadsheet Response',
                'ordering': ['-created_at'],
            },
        ),
    ]
