# Generated by Django 6.1 on 2026-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_transactionspreadsheetbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cohort_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun Angkatan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor WhatsApp'),
        ),
    ]
