# Generated by Django 6.1 on 2026-08-23 04:16

import uuid

from django.db import migrations, models


def populate_transaction_idempotency_keys(apps, schema_editor):
    Transaction = apps.get_model('registration', 'Transaction')

    for transaction_obj in Transaction.objects.filter(idempotency_key__isnull=True):
        transaction_obj.idempotency_key = f"PAY-{uuid.uuid4().hex[:20].upper()}"
        transaction_obj.save(update_fields=['idempotency_key'])

    for transaction_obj in Transaction.objects.filter(idempotency_key=''):
        transaction_obj.idempotency_key = f"PAY-{uuid.uuid4().hex[:20].upper()}"
        transaction_obj.save(update_fields=['idempotency_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_transaction_cohort_year_transaction_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Gagal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_callback_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload Callback Gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_response_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload Response Gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Status Gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ID Transaksi Gateway'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Lunas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_channel',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Channel Pembayaran'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_redirect_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Redirect URL Payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tipe Pembayaran'),
        ),
        migrations.RunPython(populate_transaction_idempotency_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=80, unique=True),
        ),
    ]
