# Generated by Django 6.1 on 2026-08-29 06:20

from django.db import migrations, models


def migrate_legacy_tshirt_sizes(apps, schema_editor):
    Ticket = apps.get_model('registration', 'Ticket')
    Ticket.objects.filter(tshirt_size='XXL+').update(tshirt_size='3XL')


def restore_legacy_tshirt_sizes(apps, schema_editor):
    Ticket = apps.get_model('registration', 'Ticket')
    Ticket.objects.filter(tshirt_size='3XL').update(tshirt_size='XXL+')


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_transaction_payment_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='', max_length=2, verbose_name='Jenjang'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='study_program',
            field=models.CharField(blank=True, choices=[('ILMU_KOMPUTER', 'Ilmu Komputer'), ('SISTEM_INFORMASI', 'Sistem Informasi'), ('KECERDASAN_ARTIFISIAL', 'Kecerdasan Artifisial'), ('TEKNOLOGI_INFORMASI', 'Teknologi Informasi')], default='', max_length=40, verbose_name='Program Studi'),
        ),
        migrations.RunPython(migrate_legacy_tshirt_sizes, restore_legacy_tshirt_sizes),
        migrations.AlterField(
            model_name='ticket',
            name='tshirt_size',
            field=models.CharField(choices=[('NONE', 'Tidak Ada Kaos'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], default='NONE', max_length=10),
        ),
    ]
