# Generated by Django 6.1 on 2026-08-29 06:31

from django.db import migrations, models


def migrate_xxl_to_3xl(apps, schema_editor):
    Ticket = apps.get_model('registration', 'Ticket')
    Ticket.objects.filter(tshirt_size='XXL').update(tshirt_size='3XL')


def restore_3xl_to_xxl(apps, schema_editor):
    Ticket = apps.get_model('registration', 'Ticket')
    Ticket.objects.filter(tshirt_size='3XL').update(tshirt_size='XXL')


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_transaction_degree_level_transaction_study_program_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_xxl_to_3xl, restore_3xl_to_xxl),
        migrations.AlterField(
            model_name='ticket',
            name='tshirt_size',
            field=models.CharField(choices=[('NONE', 'Tidak Ada Kaos'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('3XL', '3XL')], default='NONE', max_length=10),
        ),
    ]
