# Generated by Django 6.0.5 on 2026-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_ticket_tshirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='attendee_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nama Depan Peserta (Pax)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nama Belakang Peserta (Pax)'),
        ),
    ]
