# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_remove_ticket_attendee_name_ticket_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING_PAYMENT', 'Menunggu Pembayaran'),
                    ('PENDING_CONFIRMATION', 'Menunggu Konfirmasi'),
                    ('PAID', 'Sukses'),
                    ('FAILED', 'Gagal'),
                    ('EXPIRED', 'Kedaluwarsa'),
                    ('CANCELLED', 'Pesanan Dibatalkan'),
                ],
                default='PENDING_PAYMENT',
                max_length=20,
            ),
        ),
    ]
