# Generated by Django 6.0.5 on 2026-09-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_transaction_expired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Mahasiswa Aktif'), ('ALUMNI', 'Mahasiswa/Alumni')], default='ALUMNI', max_length=10),
        ),
    ]
