# Generated by Django 6.1 on 2026-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='package_type',
            field=models.CharField(choices=[('ALUMNI_PACK', 'Paket Premium (Rp 200.000)'), ('STUDENT_PACK', 'Paket Mahasiswa (Rp 125.000)'), ('TICKET_ONLY', 'Paket Basic (Rp 50.000)')], max_length=20),
        ),
    ]
