# Generated by Django 6.1 on 2026-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_update_package_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Laki-laki'), ('FEMALE', 'Perempuan')], default='', max_length=10, verbose_name='Jenis Kelamin'),
        ),
    ]
