# Generated by Django 6.1 on 2026-09-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_add_transaction_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='gender',
        ),
    ]
