# Generated by Django 6.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_add_transaction_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Admin'),
                    ('STUDENT', 'Mahasiswa Aktif'),
                    ('LECTURER', 'Dosen'),
                    ('ALUMNI', 'Mahasiswa/Alumni'),
                ],
                default='ALUMNI',
                max_length=10,
            ),
        ),
    ]
