# Generated by Django 6.1 on 2026-09-10 13:53

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_add_lecturer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_payment_proof',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.manual_payment_proof_path, verbose_name='Bukti Pembayaran Manual'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manual_payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Upload Bukti'),
        ),
    ]
