# Generated by Django 6.1 on 2026-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_transaction_manual_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tshirt_size',
            field=models.CharField(choices=[('NONE', 'Tidak Ada Kaos'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL')], default='NONE', max_length=10),
        ),
    ]
