# Generated by Django 6.1 on 2026-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_ticket_tshirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Ditandai Kedaluwarsa'),
        ),
    ]
