# Generated by Django 6.0.5 on 2026-09-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_transaction_invoice_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='package_type',
            field=models.CharField(choices=[('ALUMNI_PACK', 'Paket Premium (Rp 200.000)'), ('STUDENT_PACK', 'Paket Mahasiswa (Rp 125.000)'), ('TICKET_ONLY', 'Paket Basic (Rp 50.000)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='study_program',
            field=models.CharField(blank=True, choices=[('ILMU_KOMPUTER', 'Ilmu Komputer'), ('SISTEM_INFORMASI', 'Sistem Informasi'), ('KECERDASAN_ARTIFISIAL', 'Kecerdasan Artifisial'), ('TEKNOLOGI_INFORMASI', 'Teknologi Informasi'), ('SISTEM_INFORMASI_EKSTENSI', 'Sistem Informasi (Ekstensi)')], default='', max_length=40, verbose_name='Program Studi'),
        ),
    ]
